#!/bin/bash

CRED="\e[1;31m"
CGREEN="\e[1;32m"
CYELLOW="\e[1;33m"
CBLUE="\e[1;34m"
CMAGENTA="\e[1;35m"
CCYAN="\e[1;36m"
CEND="\e[0m"

CSUCCESS="$CGREEN"
CFAILURE="$CRED"
CQUESTION="$CMAGENTA"
CWARNING="$CYELLOW"
CMSG="$CCYAN"
